//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.FLExTransRuleGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneratorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneratorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.FLExTransRuleGenerator.Properties.GeneratorStrings", typeof(GeneratorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLExTransRuleGenerator &lt;rule-file&gt; &lt;source-FLEx-project&gt; &lt;target-FLEx-project&gt;.
        /// </summary>
        internal static string CommandLineTemplate {
            get {
                return ResourceManager.GetString("CommandLineTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tool to help write FLExTrans transfer rules..
        /// </summary>
        internal static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;rule-file&gt;  Specifies the FLExTrans transfer rule file..
        /// </summary>
        internal static string RuleFile {
            get {
                return ResourceManager.GetString("RuleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule file could not be found..
        /// </summary>
        internal static string RuleFileNotFound {
            get {
                return ResourceManager.GetString("RuleFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source FieldWorks project file could not be found..
        /// </summary>
        internal static string SourceFLExProjectNotFound {
            get {
                return ResourceManager.GetString("SourceFLExProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;source-FLEx--project&gt;  Specifies the source FieldWorks project path..
        /// </summary>
        internal static string SourceProject {
            get {
                return ResourceManager.GetString("SourceProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target FieldWorks project file could not be found..
        /// </summary>
        internal static string TargetFLExProjectNotFound {
            get {
                return ResourceManager.GetString("TargetFLExProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;target-FLEx--project&gt;  Specifies the source FieldWorks project path..
        /// </summary>
        internal static string TargetProject {
            get {
                return ResourceManager.GetString("TargetProject", resourceCulture);
            }
        }
    }
}
