//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.FLExTransRuleGen.Controller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RuleGenStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RuleGenStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIL.FLExTransRuleGen.Controller.Properties.RuleGenStrings", typeof(RuleGenStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string cmDelete {
            get {
                return ResourceManager.GetString("cmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        internal static string cmDuplicate {
            get {
                return ResourceManager.GetString("cmDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string cmEdit {
            get {
                return ResourceManager.GetString("cmEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new after.
        /// </summary>
        internal static string cmInsertAfter {
            get {
                return ResourceManager.GetString("cmInsertAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new before.
        /// </summary>
        internal static string cmInsertBefore {
            get {
                return ResourceManager.GetString("cmInsertBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert category.
        /// </summary>
        internal static string cmInsertCategory {
            get {
                return ResourceManager.GetString("cmInsertCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert feature.
        /// </summary>
        internal static string cmInsertFeature {
            get {
                return ResourceManager.GetString("cmInsertFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert prefix.
        /// </summary>
        internal static string cmInsertPrefix {
            get {
                return ResourceManager.GetString("cmInsertPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new prefix after.
        /// </summary>
        internal static string cmInsertPrefixAfter {
            get {
                return ResourceManager.GetString("cmInsertPrefixAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new prefix before.
        /// </summary>
        internal static string cmInsertPrefixBefore {
            get {
                return ResourceManager.GetString("cmInsertPrefixBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert suffix.
        /// </summary>
        internal static string cmInsertSuffix {
            get {
                return ResourceManager.GetString("cmInsertSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new suffix after.
        /// </summary>
        internal static string cmInsertSuffixAfter {
            get {
                return ResourceManager.GetString("cmInsertSuffixAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new suffix before.
        /// </summary>
        internal static string cmInsertSuffixBefore {
            get {
                return ResourceManager.GetString("cmInsertSuffixBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as head.
        /// </summary>
        internal static string cmMarkAsHead {
            get {
                return ResourceManager.GetString("cmMarkAsHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        internal static string cmMoveDown {
            get {
                return ResourceManager.GetString("cmMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move left.
        /// </summary>
        internal static string cmMoveLeft {
            get {
                return ResourceManager.GetString("cmMoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move right.
        /// </summary>
        internal static string cmMoveRight {
            get {
                return ResourceManager.GetString("cmMoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        internal static string cmMoveUp {
            get {
                return ResourceManager.GetString("cmMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove head marking.
        /// </summary>
        internal static string cmRemoveHeadMarking {
            get {
                return ResourceManager.GetString("cmRemoveHeadMarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLExTrans Rule Generator.
        /// </summary>
        internal static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Name:.
        /// </summary>
        internal static string RuleName {
            get {
                return ResourceManager.GetString("RuleName", resourceCulture);
            }
        }
    }
}
